### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by devinberg** [danielhatton/eights#1]
*Part of the peer-review for JOSS: https://github.com/openjournals/joss-reviews/issues/974*

The [JOSS criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#software-license) specify that the software license should be located in a file called `LICENSE`. Currently this information is contained within `COPYING.txt` and `COPYING_ANNEX.txt`.

**Comment by danielhatton** [comment]
Thanks for the heads-up, @devinberg.  I believe this issue to be resolved by the latest set of commits on the master branch.
