### ISSUE TITLE
Documentation missing Statement of Need

### ISSUE THREAD

**Issue by devinberg** [danielhatton/eights#2]
*Part of the peer-review for JOSS: https://github.com/openjournals/joss-reviews/issues/974*

According to the [JOSS criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#a-statement-of-need), the software's documentation, found in `Documentation.txt`, should include a Statement of Need indicating "what problems the software is designed to solve and who the target audience is." This is partially addressed in the DESCRIPTION paragraph of the documentation file. However, that section is missing information on target audience.

**Comment by danielhatton** [comment]
A "statement of need" section, largely copied from the JOSS manuscript, has now been added to the "Documentation.txt" file.  I will, however, leave this issue open, pending @devinberg's confirmation that the added section adequately resolves the issue.

**Comment by devinberg** [comment]
Great, thanks!

Closed with 4059957
