### ISSUE TITLE
Missing Community Guidelines

### ISSUE THREAD

**Issue by devinberg** [danielhatton/eights#3]
*Part of the peer-review for JOSS: https://github.com/openjournals/joss-reviews/issues/974*

The [JOSS criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) specify that the repo should contain "Contributing guidelines" which provide direction for anyone wishing to contribute, report issues, or seek support. This information might normally be found in a file called `CONTRIBUTING`.

**Comment by danielhatton** [comment]
Thanks, @devinberg.  I'll familiarize myself with what forms of collaborative editing are possible (or can be made possible by adjusting permissions settings) on GitHub, and compose something appropriate.  It may take a while.....

**Comment by devinberg** [comment]
An example of a relatively minimal contributing document can be found here: https://gitlab.com/moorepants/skijumpdesign/blob/master/CONTRIBUTING

**Comment by danielhatton** [comment]
In the latest commit, I've added a `CONTRIBUTING` file containing some appropriate guidance.  I've also created a new release, since I believe this completes addressing everything raised both here and in the "Installation and testing" issue thread.

**Comment by devinberg** [comment]
Thank you for this revision.
