### ISSUE TITLE
Installation and testing

### ISSUE THREAD

**Issue by devinberg** [danielhatton/eights#4]
*Part of the peer-review for JOSS: https://github.com/openjournals/joss-reviews/issues/974*

I've been working through the installation and documentation. I was able to use `eights.py` by placing it in the macros directory. However, I was not able to get it to work by saving the file in the working directory.

Could you help me better understand what I should be seeing as output?

I was able to get a drawing to generate (see [here](https://github.com/danielhatton/eights/files/2412779/Two_parts.pdf)) using `Two_parts.py` but not with `Single_part.py` or `Assembly.py`.

**Comment by danielhatton** [comment]
Can I have some further information to help debug, please?  In particular:

- On what operating system and FreeCAD version were you testing (I'm currently on FreeCAD 0.16 for Scientific Linux 7.5, and it works for me)?

- How did you launch FreeCAD in such a way as to give it a particular working directory (I'm currently launching FreeCAD from a bash command line with the directory in question as working directory, and it works for me)?

- Did you run Single_part.py and/or Assembly.py from a freshly-launched FreeCAD instance, or from a FreeCAD instance that already had some documents open from a previous run of Two_parts.py (it works for me in the first case, but not the second)?

I've made copies (via "print to file" in the FreeCAD GUI) of the outputs I get from Single_part.py and Assembly.py, but every time I try to attach them to this comment, I get a message from GitHub saying 'Something went really wrong, and we can't process that file'.  I'll try it again tomorrow, from a different network environment.

**Comment by devinberg** [comment]
I've tried this on Windows 10 with both FreeCAD 0.17 and 0.15. Version 0.17 doesn't appear to work completely as intended, but 0.15 I think does. However, I'd like to see your output so I know if I'm getting the correct thing.

In general, I think your documentation would be improved by providing this sort of benchmark to allow users to make sure the software is working as intended on their system. The JOSS criteria describes automated tests which might not make sense in this case. However, I think you could take your example documents and provide those with the intended output as a way of helping users test their system.

This might be easier to do if you migrated your `documentation.txt` file to a `README.md` file. Then you could include some screenshots showing the intended output for a test input, providing users a comparison point.

**Comment by danielhatton** [comment]
Here are the intended outputs from Single_part.py and Assembly.py:
[Single_part.pdf](https://github.com/danielhatton/eights/files/2492355/Single_part.pdf)

[Assembly.pdf](https://github.com/danielhatton/eights/files/2492353/Assembly.pdf)

Yes, that's a good idea about including them in the project tree for benchmarking.

**Comment by devinberg** [comment]
@danielhatton Thanks for providing those. Only difference I'm seeing when I run the examples is the positioning of the text in the title block. See below where the text is double spaced and the info on sheet size, part number and such has moved to different boxes. Any ideas what would be causing that?

I'm running version 0.15 and using the example code you provide.

![assembly_title_block](https://user-images.githubusercontent.com/1399027/47175462-c71aee80-d2d8-11e8-8054-368261fbda37.PNG)

**Comment by danielhatton** [comment]
@devinberg:

> Only difference I'm seeing when I run the examples is the positioning of the text in the title block.

Thanks, @devinberg .  This problem with the placement of fields in the title block in FreeCAD version 0.15 was described in the "bugs" section of the original Documentation.txt file as follows:

> If run under FreeCAD 0.15 (or earlier), the create_it method in the
> create_eights_drawing_sheet class incorrectly places the various items
> of text information correctly in the title block of the
> Drawing::FeaturePage object it creates.  That's because the number and
> order of elements, in the EditableTexts property of a
> Drawing::FeaturePage object using an ISO7200 template, changed between
> FreeCAD 0.15 and FreeCAD 0.16, and this version of the present module
> is tuned to place the text information correctly under FreeCAD 0.16.

However, I believe that, in the latest set of commits, I've fixed this bug (by having the eights.py module detect the FreeCAD version number under which it's running, and assign different title block fields to different array elements of the EditableTexts property depending on whether the version number is less than or greater than 0.155).  Therefore, also in the latest set of commits, I've deleted that paragraph from the "bugs" section of the Documentation.txt file.

**Comment by danielhatton** [comment]
@devinberg :

> However, I think you could take your example documents and provide those with the intended output
> as a way of helping users test their system...
> This might be easier to do if you migrated your `documentation.txt` file to a `README.md` file. Then
> you could include some screenshots showing the intended output for a test input, providing users a
> comparison point.

In the latest set of commits, I have indeed replaced `documentation.txt` with a `README.md` file which includes embedded images of the intended outputs from the example scripts.

**Comment by danielhatton** [comment]
@devinberg 

> I was able to use `eights.py` by placing it in the macros directory. However, I was not able to get it to
> work by saving the file in the working directory.

In the new `README.md` file, uploaded as part of the latest set of commits, I've clarified the "Installation" section to take account of this information.

**Comment by danielhatton** [comment]
@devinberg 
> I've tried this on Windows 10 with both FreeCAD 0.17 and 0.15. Version 0.17 doesn't appear to work
> completely as intended, but 0.15 I think does.

Given what we both said later in the thread about the placement of fields in the title block, I suspect it might have been the other way round, and that in any case, the difference will have gone away in the new release.  I've just run all three example scripts on FreeCAD 0.17 under Fedora 29, and the results were as intended.

**Comment by danielhatton** [comment]
@danielhatton 
> I've made copies (via "print to file" in the FreeCAD GUI) of the outputs I get from Single_part.py and
> Assembly.py, but every time I try to attach them to this comment, I get a message from GitHub
> saying 'Something went really wrong, and we can't process that file'. I'll try it again tomorrow, from a
> different network environment.

Just in case anyone else is trying to debug a similar error message to this one, I've been investigating its origin, and it appears to result from the fact that the "family filter" on my home ADSL connection, as currently configured, blocks access to anything in the domain `s3.amazonaws.com`; it looks like, without access to that domain, it's not possible either to upload or to download files attached to comments in issue threads on GitHub.  I can work around it by simply doing my uploads and downloads from a different network environment.

**Comment by devinberg** [comment]
@danielhatton 

> Given what we both said later in the thread about the placement of fields in the title block, I suspect it might have been the other way round, and that in any case, the difference will have gone away in the new release. 

I actually had trouble getting it to run at all on Windows 10 using FreeCAD 0.17 but I couldn't say with certainty that it wasn't an issue with my setup. Also, since your Prerequisites specify you've only tested version 0.15 on Windows, I don't think this is a big deal as far as the JOSS review is concerned. Thanks for your edits in the latest release.

**Comment by danielhatton** [comment]
@devinberg 

> I actually had trouble getting it to run at all on Windows 10 using FreeCAD 0.17

Earlier today, I installed FreeCAD 0.17 on a Windows 10 machine, and I was able to get all three example scripts for `eights` to run correctly, but only after I'd restarted FreeCAD a couple of times to get it to recognise that there was a module called `eights` in its macros directory.  `README.md` already mentions that a restart of FreeCAD is sometimes needed to complete the installation of the `eights` module, but I think I'll add a comment to the effect that it sometimes needs to be restarted twice.
