### ISSUE TITLE
What is this project exactly?

### ISSUE THREAD

**Issue by luzpaz** [danielhatton/eights#5]
And would you be open to showcasing it on the FreeCAD User Showcase subforum?

**Comment by luzpaz** [comment]
Didn't see the https://github.com/danielhatton/eights/blob/master/Documentation.txt page. Are you planning to have a README.md file?

**Comment by danielhatton** [comment]
Thanks for stopping by, @luzpaz , and please accept my apologies for the severely delayed reply.  Yes, there is now a `README.md` file.
Being an academic, I (and my employer) like to announce things in a peer-reviewed journal first, and an announcement of the existence of this project is currently undergoing refereeing at the Journal of Open Source Software (the other issue threads on here are part of the refereeing process).  However, once that's done, I'd be very happy indeed to showcase the project on the FreeCAD User Showcase subforum: I'm guessing you mean the one at <https://forum.freecadweb.org/viewforum.php?f=24&sid=7799800fd4631a6054f6301ebf68ea80>...?

**Comment by danielhatton** [comment]
This module has now been the subject of quite a lively discussion on the FreeCAD forums (the "Python scripting and macros" section, rather than the "user projects" section), so I think it's safe to close the issue.
